-- AlterTable
ALTER TABLE "HotelComplex" ALTER COLUMN "hotelChain" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "province" DROP NOT NULL,
ALTER COLUMN "region" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "latitude" DROP NOT NULL,
ALTER COLUMN "longitude" DROP NOT NULL,
ALTER COLUMN "rooms" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TechnicalInstallation" ADD COLUMN     "pvPowerKw" DOUBLE PRECISION,
ALTER COLUMN "type" DROP NOT NULL;
